{
  "name": "test",
  "edited": "08/10/23, 07:34 PM",
  "isRed": false,
  "paths": [
    {
      "name": "new path 1",
      "id": "c34f979d-eff4-4565-9a4e-5c45ef7e5a7c",
      "isSpline": true,
      "maxVelocity": 3.0,
      "maxAcceleration": 2.0,
      "snapToPrevious": false,
      "points": [
        {
          "x": 5.09087,
          "y": 1.69726,
          "rotation": 180.0,
          "id": "6bbf554a-5913-47c0-8c2c-fa81cb60415d"
        },
        {
          "x": 4.7526,
          "y": 4.1467,
          "rotation": 200.0,
          "id": "a599da2c-0e4c-41f7-920e-273515e7a130"
        },
        {
          "x": 5.64563,
          "y": 5.00772,
          "rotation": 200.0,
          "id": "5f096493-96ee-4818-84cc-ea61c82f1b31"
        },
        {
          "x": 5.38855,
          "y": 6.49222,
          "rotation": 200.0,
          "id": "b8f66fbc-96a6-42a0-a05d-0c4cb3dda6ad"
        },
        {
          "x": 4.80672,
          "y": 5.67574,
          "rotation": -169.0,
          "id": "91078d08-1f3e-4e4f-b077-6f43d15c067d"
        },
        {
          "x": 5.26677,
          "y": 3.41929,
          "rotation": 180.0,
          "id": "5a572b0d-7d92-44c0-8db5-8d592dcbe774"
        },
        {
          "x": 5.091,
          "y": 1.697,
          "rotation": 180.0,
          "id": "3a5b58a6-04c4-4465-9a53-4cb75b43cc70"
        }
      ]
    }
  ]
}